apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: final
  labels:
    app: employees
spec:
  type: LoadBalancer
  ports:
    - port: 81
      targetPort: 81
  selector:
    app: employees