apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 113222697619.dkr.ecr.us-east-1.amazonaws.com/clo835-database:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        envFrom:
          - secretRef:
              name: mysql-secret
        ports:
        - containerPort: 3306
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data

          