apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  namespace: application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: web-app
        image: 357367068747.dkr.ecr.us-east-1.amazonaws.com/clo835-app:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "mysql-service.database.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DATABASE
          value: "employees"
        - name: DBPWD
          value: "pw"
        - name: APP_COLOR
          value: "blue"