apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: application
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: 357367068747.dkr.ecr.us-east-1.amazonaws.com/clo835-app:v1
    ports:
    - containerPort: 8080
    env:
    - name: DBHOST
      value: "mysql-service.database.svc.cluster.local"
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DATABASE
      value: "employees"
    - name: DBPWD
      value: "pw"
    - name: APP_COLOR
      value: "blue"