apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 357367068747.dkr.ecr.us-east-1.amazonaws.com/clo835-db:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pw"
        ports:
        - containerPort: 3306