apiVersion: v1
kind: ConfigMap
metadata:
  name: url-config
  namespace: final
data:
  Group_Name: Group3
  Image_Uri: grp3wall.jpg
  region: us-east-1
  bucketname: grp3project-bucket
  
  #Images that been used in the assignment: images.jpg,  success.jpg