apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-mysql
  namespace: final
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/component: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/component: frontend
    spec:
      serviceAccountName: clo835
      containers:
      - name: simple-webapp-mysql
        image: 212825301706.dkr.ecr.us-east-1.amazonaws.com/finalgroup25-repo:v0.2   #replace URI of current ac
        imagePullPolicy: Always
        env:
        - name: GROUP_NAME
          valueFrom: 
            configMapKeyRef:
              name: url-config
              key: Group_Name
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: url-config
              key: region
        - name: S3_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: url-config
              key: bucketname
        # - name: Image_Uri
        #   valueFrom:
        #     configMapKeyRef:
        #       name: url-config
        #       key: Image_Uri
        #args: ["$Image_Uri"]
        ports:
        - containerPort: 81
        volumeMounts:
        - name: app-secret-volumes
          mountPath: /opt/app-secret-volumes
          readOnly: true
        - name: config-volume
          mountPath: /clo835/config
        envFrom:
        - configMapRef:
           name: url-config
        - secretRef:
           name: db-secret
      volumes:
      - name: app-secret-volumes
        secret:
          secretName: db-secret
      - name: config-volume
        configMap: 
          name: url-config
          items:
              - key: Image_Uri
                path: Image_Uri